spring.application.name=user-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/social_media_user}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456789}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true


keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8088}


keycloak.realm=${KEYCLOAK_REALM:social-media-realm}


keycloak.client-id=${KEYCLOAK_CLIENT_ID:social-media-frontend}


keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}


keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin123}


internal.auth.secret=${INTERNAL_AUTH_SECRET:change-me-in-production}

spring.rabbitmq.listener.simple.acknowledge-mode=manual


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.file.name=logs/${spring.application.name}.log
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
