services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - social-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - social-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo.yml
    # KHÔNG mở cổng 4318 ra ngoài nữa, để Otel-Collector lo giao tiếp nội bộ
    ports:
      - "3200:3200"
    networks:
      - social-network

  loki:
    image: grafana/loki:2.9.10
    container_name: loki
    restart: always
    command: [ "-config.file=/etc/loki/loki-config.yml" ] # Đồng bộ đuôi .yml
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki # Thêm volume để lưu trữ log không bị mất khi restart
    networks:
      - social-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    command: [ "-config.file=/etc/promtail/promtail-config.yml" ]
    volumes:
      - ./observability/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/logs
    depends_on:
      - loki
    networks:
      - social-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./observability/otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4319:4318"  # Máy host gọi vào 4319 -> chạy vào cổng HTTP 4318 của Collector
    depends_on:
      - tempo
    networks:
      - social-network

networks:
  social-network:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  loki_data: # Khai báo thêm để lưu log database của Loki