spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# observability
eureka.server.response-cache-update-interval-ms=1000
spring.jersey.type=filter
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.sampling.probability=1.0
management.endpoint.health.show-details=always
management.otlp.tracing.endpoint=http://localhost:4319/v1/traces
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
logging.file.name=logs/${spring.application.name}.log
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]