spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

jwt.base64-secret=uzDAqPUp8jZPdEOsTpm4IeZ=rOCmSfi=nLQn2pSMg/DcjJAoOKZbEavb5y0Khk=!nZk8BIxTT8Z!7=x=aH7sTC/V0QdY7B4z6lKKIAO69nzKxBhrrA=?=uKIyHqea2iKW0P1hzHj5A=A1dvZAIk1m!pyK0X9F2HB6HXxjP8ZoQduA20JNmYHP?T/eH!EnTYtOUiUIzdV-oMAvvp7uec5CaJapMJmtrRh0whA?8NiL38kQBGk4z4-bOOrzKrU!!/Q

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/friends/**,/api/v1/friend-requests/**,/api/v1/blocks/**,/api/v1/admin/**

spring.cloud.gateway.routes[1].id=interaction-service
spring.cloud.gateway.routes[1].uri=lb://interaction-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/posts/*/comments/**,/api/v1/posts/*/react,/api/v1/posts/*/reactions,/api/v1/posts/*/me,/api/v1/posts/*/un-react,/api/v1/comments/**

spring.cloud.gateway.routes[2].id=post-service
spring.cloud.gateway.routes[2].uri=lb://post-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/posts/**,/api/v1/files/**,/api/v1/groups/*/posts/**

spring.cloud.gateway.routes[3].id=group-service
spring.cloud.gateway.routes[3].uri=lb://group-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/groups/**

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/notifications/**,/ws/notifications/**
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

management.endpoints.web.exposure.include=health,info,metrics
