spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8088/realms/social-media-realm}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8088/realms/social-media-realm/protocol/openid-connect/certs}

spring.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.cloud.gateway.routes[0].id=interaction-service
spring.cloud.gateway.routes[0].uri=lb://interaction-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/posts/*/comments/**,/api/v1/posts/*/react,/api/v1/posts/*/reactions,/api/v1/posts/*/me,/api/v1/posts/*/un-react,/api/v1/posts/*/counts,/api/v1/comments/**

spring.cloud.gateway.routes[1].id=post-service
spring.cloud.gateway.routes[1].uri=lb://post-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/users/*/posts,/api/v1/posts,/api/v1/posts/*,/api/v1/posts/*/shares,/api/v1/posts/*/shares/*,/api/v1/files/**,/api/v1/groups/*/posts/**

spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=lb://user-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/friends/**,/api/v1/friend-requests/**,/api/v1/blocks/**,/api/v1/admin/**

spring.cloud.gateway.routes[3].id=group-service
spring.cloud.gateway.routes[3].uri=lb://group-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/groups/**

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/notifications/**,/ws/notifications/**

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.file.name=logs/${spring.application.name}.log
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
